### ISSUE TITLE
Unclosed Issues

### ISSUE THREAD

**Issue by TheodorKitzenmaier** [pwncollege/dojo#905]
Over time, there are several issues which have been addressed but have not been closed. This issue will attempt to identify some of these issues so they can be further reviewed and closed if necessary. Additional issues will be added to the list as I continue to review issues.

#865 has a PR which supposedly could close it.

#835 has a Yolo fix?

#827 should be closed by #828.

#818 should be closed by #872.

#788?

#764 has a potential solution.

#749 seems to be resolved (the CI isn't constantly failing).

#739 should be closed by #743.

#704 should be closed by #747.

#702 seems like a dead end.

**Comment by zrayaz1** [comment]
#788 was fixed in [challenge-images](https://github.com/pwncollege/challenge-images/commit/f536f536cc06fb6e5cd8345f96c9f7adada3b2d8#diff-2ff1bda5e6bc2f5db0802921d1cdeb78cd6aa984c2f8d55464e0a4989c1ddd68L161)

**Comment by robwaz** [comment]
I reviewed the PRs listed and concluded the following after reviewing them.

#835 Closed
#827 Closed
#818 is still an issue
#788 is still an issue in a specific case
#764 is still relevant, the core issue should be cleanly resolved
#749 Closed
#739 Closed
#704 Closed
#702 Still an issue, we could close it as a no-fix

**Comment by zrayaz1** [comment]
#788  should be fixed for real this time. #934 
#810 has a workaround fix #919 
#674 happened with #734 

#564 nix gdb debug symbols should be fixed with #724 I'm not sure if the second libc issue mentioned is still relevant.
#561 this happened with the update to 25.05
